# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/ANOOBIS/UnrealEngine

TARGETS = \
	KitchenPanic-Android-DebugGame  \
	KitchenPanic-Android-Development  \
	KitchenPanic-Android-Shipping  \
	KitchenPanic-Linux-DebugGame  \
	KitchenPanic-Linux-Development  \
	KitchenPanic-Linux-Shipping  \
	KitchenPanic-LinuxArm64-DebugGame  \
	KitchenPanic-LinuxArm64-Development  \
	KitchenPanic-LinuxArm64-Shipping  \
	KitchenPanic \
	KitchenPanicEditor-Linux-DebugGame  \
	KitchenPanicEditor-Linux-Development  \
	KitchenPanicEditor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend KitchenPanicEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug KitchenPanicEditor-Linux-Debug


KitchenPanic-Android-DebugGame:
	 $(BUILD) KitchenPanic Android DebugGame  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanic-Android-Development:
	 $(BUILD) KitchenPanic Android Development  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanic-Android-Shipping:
	 $(BUILD) KitchenPanic Android Shipping  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanic-Linux-DebugGame:
	 $(BUILD) KitchenPanic Linux DebugGame  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanic-Linux-Development:
	 $(BUILD) KitchenPanic Linux Development  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanic-Linux-Shipping:
	 $(BUILD) KitchenPanic Linux Shipping  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanic-LinuxArm64-DebugGame:
	 $(BUILD) KitchenPanic LinuxArm64 DebugGame  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanic-LinuxArm64-Development:
	 $(BUILD) KitchenPanic LinuxArm64 Development  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanic-LinuxArm64-Shipping:
	 $(BUILD) KitchenPanic LinuxArm64 Shipping  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanic: KitchenPanic-Linux-Development

KitchenPanicEditor-Linux-DebugGame:
	 $(BUILD) KitchenPanicEditor Linux DebugGame  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanicEditor-Linux-Development:
	 $(BUILD) KitchenPanicEditor Linux Development  -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" $(ARGS)

KitchenPanicEditor: KitchenPanicEditor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/ANOOBIS/Desktop/Game Dev/UE PROJECTS/KitchenPanic/KitchenPanic.uproject" -Game 

.PHONY: $(TARGETS)
